check_payload = ('{"source":{'
                 '"bucket":"bucketName",'
                 '"access_key_id":"apiKey123",'
                 '"secret_access_key":"secretKey321",'
                 '"region_name":"eu-west-1",'
                 '"filename":"release-'
                 '"},'
                 '"version":{"version":"release-1.0.0.tar.gz"}}')
check_payload_without_version = ('{"source":{'
                                 '"bucket":"bucketName",'
                                 '"access_key_id":"apiKey123",'
                                 '"secret_access_key":"secretKey321",'
                                 '"region_name":"eu-west-1",'
                                 '"filename":"release-'
                                 '"}}')
in_payload = ('{"source":{'
              '"bucket":"bucketName",'
              '"access_key_id":"apiKey123",'
              '"secret_access_key":"secretKey321",'
              '"region_name":"eu-west-1",'
              '"filename":"release-'
              '"},'
              '"version":{"version":"release-1.0.0.tar.gz"}}')
in_payload_without_version = ('{"source":{'
                              '"bucket":"bucketName",'
                              '"access_key_id":"apiKey123",'
                              '"secret_access_key":"secretKey321",'
                              '"region_name":"eu-west-1",'
                              '"filename":"release-'
                              '"}}')
out_payload = ('{"params":{'
               '"version":"version/name",'
               '"folderpath":"artifact/'
               '"},'
               '"source":{'
               '"bucket":"bucketName",'
               '"access_key_id":"apiKey123",'
               '"filename":"release-",'
               '"secret_access_key":"secretKey321",'
               '"region_name":"eu-west-1'
               '"},'
               '"version":{"version":"release-1.0.0.tar.gz"}}')
out_payload_without_version = ('{"params":{'
                               '"version":"version/name",'
                               '"folderpath":"artifact/'
                               '"},'
                               '"source":{'
                               '"bucket":"bucketName",'
                               '"access_key_id":"apiKey123",'
                               '"filename":"release-",'
                               '"secret_access_key":"secretKey321",'
                               '"region_name":"eu-west-1'
                               '"}}')
